version: '3.1'
services: 
    tomcat1:
        image: priya93/maventest1
        restart: always
        container_name: container1
        ports:
         - 8080:8080
         working_dir: /opt/app
        depends_on:
         - tomcat2
        deploy:
         replicas: 2
         update_config:
         parallelism: 2
         delay: 10s
         restart_policy:
         condition: on-failure 
        
    tomcat2:
        image: priya93/maventest2
        container_name: container2
#    ports:  # for demo/debug purpose only
#      - 27018:27017
        volumes:
         - data:/data/db
        - data-bkp:/data/bkp
         restart: always
    
volumes:
  data:
    external: true
  data-bkp:
    external: true
