version: '3.1'
  
services:
  springboot:
    image: priya93/maventest1
    container_name: springboot
    ports:
      - 8182:8080
    working_dir: /opt/app
    depends_on:
      - mongo
   

  mongo:
    image: priya93/maventest2
    container_name: mongo
#    ports:  # for demo/debug purpose only
#      - 27018:27017
    volumes:
      - data:/data/db
      - data-bkp:/data/bkp
    restart: always

volumes:
    data:
    data-bkp:
networks:
  default:
